// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// write_bed_cpp
void write_bed_cpp(const char* fo, IntegerMatrix X);
RcppExport SEXP _genio_write_bed_cpp(SEXP foSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char* >::type fo(foSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type X(XSEXP);
    write_bed_cpp(fo, X);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genio_write_bed_cpp", (DL_FUNC) &_genio_write_bed_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_genio(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
