# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

write_bed_cpp <- function(fo, X) {
    invisible(.Call('_genio_write_bed_cpp', PACKAGE = 'genio', fo, X))
}

