# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bed_cpp <- function(file, m_loci, n_ind) {
    .Call('_genio_read_bed_cpp', PACKAGE = 'genio', file, m_loci, n_ind)
}

write_bed_cpp <- function(file, X) {
    invisible(.Call('_genio_write_bed_cpp', PACKAGE = 'genio', file, X))
}

