on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("OchoaLab/genio")
        shell: Rscript {0}

      - name: Run the code from https://github.com/OchoaLab/genio/issues/6
        run: Rscript scripts/issue_6.R

